// SPDX-License-Identifier: AGPL-3.0-only
/**
* Digital Voice Modem - Fixed Network Equipment Core Library
* AGPLv3 Open Source. Use is subject to license terms.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* @package DVM / Fixed Network Equipment Core Library
* @license AGPLv3 License (https://opensource.org/licenses/AGPL-3.0)
*
*   Copyright (C) 2026 DVMProject Authors
*
*/

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.Json;

namespace fnecore
{
    /// <summary>
    /// Event used to convey a patch status registry snapshot received from the FNE.
    /// </summary>
    public class PatchStatusReceivedEvent : EventArgs
    {
        /// <summary>
        /// Registry snapshot.
        /// </summary>
        public PatchStatusRegistrySnapshot Snapshot { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PatchStatusReceivedEvent"/> class.
        /// </summary>
        /// <param name="snapshot">Registry snapshot.</param>
        public PatchStatusReceivedEvent(PatchStatusRegistrySnapshot snapshot)
        {
            Snapshot = snapshot;
        }
    } // public class PatchStatusReceivedEvent

    /// <summary>
    /// Represents a talkgroup member participating in a console patch.
    /// </summary>
    /// <remarks>This mirrors PatchStatusRegistry::PatchMember in dvmhost.</remarks>
    public class PatchStatusMember
    {
        /// <summary>
        /// System name for the member.
        /// </summary>
        public string System { get; set; } = string.Empty;
        /// <summary>
        /// Digital mode for the member.
        /// </summary>
        /// <remarks>The FNE normalizes this to lower case.</remarks>
        public string Mode { get; set; } = "unknown";
        /// <summary>
        /// Talkgroup ID for the member.
        /// </summary>
        public uint Tgid { get; set; }
        /// <summary>
        /// Timeslot for the member, if applicable.
        /// </summary>
        public byte Slot { get; set; }
        /// <summary>
        /// Stable talkgroup lookup key generated by the FNE.
        /// </summary>
        /// <remarks>Only populated on records received from the FNE.</remarks>
        public string Key { get; set; } = string.Empty;

        /*
        ** Methods
        */

        /// <summary>
        /// Builds the stable talkgroup lookup key the FNE generates for a member.
        /// </summary>
        /// <returns>Talkgroup key in the form "mode:tgid:slot".</returns>
        public string BuildKey()
        {
            return BuildKey(Mode, Tgid, Slot);
        }

        /// <summary>
        /// Builds the stable talkgroup lookup key the FNE generates for a member.
        /// </summary>
        /// <param name="mode">Digital mode.</param>
        /// <param name="tgid">Talkgroup ID.</param>
        /// <param name="slot">Timeslot.</param>
        /// <returns>Talkgroup key in the form "mode:tgid:slot".</returns>
        public static string BuildKey(string mode, uint tgid, byte slot)
        {
            return string.Format(CultureInfo.InvariantCulture, "{0}:{1}:{2}",
                (mode ?? string.Empty).ToLowerInvariant(), tgid, (uint)slot);
        }
    } // public class PatchStatusMember

    /// <summary>
    /// Represents one console patch.
    /// </summary>
    /// <remarks>This mirrors PatchStatusRegistry::PatchRecord in dvmhost.</remarks>
    public class PatchStatusPatch
    {
        /// <summary>
        /// Console-defined patch ID.
        /// </summary>
        public string PatchId { get; set; } = string.Empty;
        /// <summary>
        /// Flag indicating whether the patch is active.
        /// </summary>
        public bool Active { get; set; } = true;
        /// <summary>
        /// Flag indicating whether the patch is one-way.
        /// </summary>
        public bool OneWay { get; set; }
        /// <summary>
        /// Talkgroup members in the patch.
        /// </summary>
        public List<PatchStatusMember> Members { get; set; } = new List<PatchStatusMember>();

        /// <summary>
        /// Console peer ID that owns the patch.
        /// </summary>
        /// <remarks>Only populated in the flattened "patches" array of a registry snapshot.</remarks>
        public uint PeerId { get; set; }
        /// <summary>
        /// FNE peer ID where the patch originated.
        /// </summary>
        /// <remarks>Only populated in the flattened "patches" array of a registry snapshot.</remarks>
        public uint OriginFnePeerId { get; set; }
        /// <summary>
        /// Console peer display name that owns the patch.
        /// </summary>
        /// <remarks>Only populated in the flattened "patches" array of a registry snapshot.</remarks>
        public string PeerName { get; set; } = string.Empty;
    } // public class PatchStatusPatch

    /// <summary>
    /// Represents a console peer's complete patch status snapshot.
    /// </summary>
    /// <remarks>This mirrors PatchStatusRegistry::PeerPatchSnapshot in dvmhost.</remarks>
    public class PatchStatusPeer
    {
        /// <summary>
        /// Console peer ID.
        /// </summary>
        public uint PeerId { get; set; }
        /// <summary>
        /// FNE peer ID where this status originated.
        /// </summary>
        public uint OriginFnePeerId { get; set; }
        /// <summary>
        /// Console peer display name.
        /// </summary>
        public string PeerName { get; set; } = string.Empty;
        /// <summary>
        /// Console-defined sequence number.
        /// </summary>
        public uint Sequence { get; set; }
        /// <summary>
        /// Time this snapshot was accepted, in milliseconds since the UNIX epoch.
        /// </summary>
        public ulong UpdatedAt { get; set; }
        /// <summary>
        /// Time this snapshot expires, in milliseconds since the UNIX epoch.
        /// </summary>
        public ulong ExpiresAt { get; set; }
        /// <summary>
        /// Complete patch list for this console peer.
        /// </summary>
        public List<PatchStatusPatch> Patches { get; set; } = new List<PatchStatusPatch>();
    } // public class PatchStatusPeer

    /// <summary>
    /// Represents a complete patch status registry snapshot received from the FNE.
    /// </summary>
    public class PatchStatusRegistrySnapshot
    {
        /// <summary>
        /// Message type reported by the FNE. This is "registry" for snapshots.
        /// </summary>
        public string Type { get; set; } = string.Empty;
        /// <summary>
        /// Monotonic registry revision.
        /// </summary>
        public ulong Revision { get; set; }
        /// <summary>
        /// Per console peer patch snapshots.
        /// </summary>
        public List<PatchStatusPeer> Peers { get; set; } = new List<PatchStatusPeer>();
        /// <summary>
        /// Flattened patch list across all console peers.
        /// </summary>
        public List<PatchStatusPatch> Patches { get; set; } = new List<PatchStatusPatch>();
        /// <summary>
        /// Patch entries indexed by the FNE generated talkgroup key.
        /// </summary>
        public Dictionary<string, List<PatchStatusPatch>> ByTalkgroup { get; set; } =
            new Dictionary<string, List<PatchStatusPatch>>();
        /// <summary>
        /// Console peer ID the FNE accepted a publish for, if this snapshot is a publish response.
        /// </summary>
        public uint AcceptedPeerId { get; set; }
        /// <summary>
        /// TTL, in seconds, the FNE applied to the accepted publish, if this snapshot is a publish response.
        /// </summary>
        public uint TtlSeconds { get; set; }
        /// <summary>
        /// Raw JSON payload as received.
        /// </summary>
        public string RawJson { get; set; } = string.Empty;

        /*
        ** Methods
        */

        /// <summary>
        /// Gets the snapshot entry for the supplied console peer ID.
        /// </summary>
        /// <param name="peerId">Console peer ID.</param>
        /// <returns><see cref="PatchStatusPeer"/> for the peer, or null if the registry holds no record.</returns>
        public PatchStatusPeer FindPeer(uint peerId)
        {
            foreach (PatchStatusPeer peer in Peers)
            {
                if (peer.PeerId == peerId)
                    return peer;
            }

            return null;
        }
    } // public class PatchStatusRegistrySnapshot

    /// <summary>
    /// Represents a console patch status publish request sent to the FNE.
    /// </summary>
    public class PatchStatusPublish
    {
        /// <summary>
        /// Console peer ID. The FNE overwrites this with the authenticated peer identity.
        /// </summary>
        public uint PeerId { get; set; }
        /// <summary>
        /// Console peer display name. The FNE substitutes the connection identity when empty.
        /// </summary>
        public string PeerName { get; set; } = string.Empty;
        /// <summary>
        /// Console-defined sequence number.
        /// </summary>
        /// <remarks>
        /// The FNE discards a publish whose sequence is less than or equal to the sequence it already
        /// holds for this peer, so a keepalive republish must advance the sequence to refresh the TTL.
        /// </remarks>
        public uint Sequence { get; set; }
        /// <summary>
        /// Requested TTL, in seconds. The FNE clamps this into its configured TTL range.
        /// </summary>
        public uint TtlSeconds { get; set; }
        /// <summary>
        /// Complete patch list for this console peer. An empty list clears the peer's registry record.
        /// </summary>
        public List<PatchStatusPatch> Patches { get; set; } = new List<PatchStatusPatch>();
    } // public class PatchStatusPublish

    /// <summary>
    /// Implements serialization for the FNE console patch status registry protocol.
    /// </summary>
    public static class PatchStatusCodec
    {
        /// <summary>
        /// Message type used to publish a complete patch snapshot.
        /// </summary>
        public const string TYPE_PUBLISH = "publish";
        /// <summary>
        /// Message type used to request the current registry snapshot.
        /// </summary>
        public const string TYPE_REQUEST = "request";
        /// <summary>
        /// Message type the FNE uses for registry snapshots.
        /// </summary>
        public const string TYPE_REGISTRY = "registry";

        /*
        ** Methods
        */

        /// <summary>
        /// Serializes a patch status publish request.
        /// </summary>
        /// <param name="publish">Publish request.</param>
        /// <returns>UTF-8 encoded JSON payload.</returns>
        public static byte[] EncodePublish(PatchStatusPublish publish)
        {
            if (publish == null)
                throw new ArgumentNullException(nameof(publish));

            using (MemoryStream stream = new MemoryStream())
            {
                using (Utf8JsonWriter writer = new Utf8JsonWriter(stream))
                {
                    writer.WriteStartObject();

                    writer.WriteString("type", TYPE_PUBLISH);
                    writer.WriteNumber("peerId", publish.PeerId);
                    writer.WriteString("peerName", publish.PeerName ?? string.Empty);
                    writer.WriteNumber("sequence", publish.Sequence);
                    writer.WriteNumber("ttlSeconds", publish.TtlSeconds);

                    writer.WriteStartArray("patches");
                    foreach (PatchStatusPatch patch in publish.Patches)
                    {
                        writer.WriteStartObject();
                        writer.WriteString("patchId", patch.PatchId ?? string.Empty);
                        writer.WriteBoolean("active", patch.Active);
                        writer.WriteBoolean("oneWay", patch.OneWay);

                        writer.WriteStartArray("members");
                        foreach (PatchStatusMember member in patch.Members)
                        {
                            writer.WriteStartObject();
                            writer.WriteString("system", member.System ?? string.Empty);
                            writer.WriteString("mode", (member.Mode ?? "unknown").ToLowerInvariant());
                            writer.WriteNumber("tgid", member.Tgid);
                            writer.WriteNumber("slot", (uint)member.Slot);
                            writer.WriteEndObject();
                        }
                        writer.WriteEndArray();

                        writer.WriteEndObject();
                    }
                    writer.WriteEndArray();

                    writer.WriteEndObject();
                }

                return stream.ToArray();
            }
        }

        /// <summary>
        /// Serializes a registry snapshot request.
        /// </summary>
        /// <returns>UTF-8 encoded JSON payload.</returns>
        public static byte[] EncodeRequest()
        {
            using (MemoryStream stream = new MemoryStream())
            {
                using (Utf8JsonWriter writer = new Utf8JsonWriter(stream))
                {
                    writer.WriteStartObject();
                    writer.WriteString("type", TYPE_REQUEST);
                    writer.WriteEndObject();
                }

                return stream.ToArray();
            }
        }

        /// <summary>
        /// Deserializes a patch status registry snapshot.
        /// </summary>
        /// <param name="json">JSON payload received from the FNE.</param>
        /// <returns><see cref="PatchStatusRegistrySnapshot"/>, or null if the payload could not be parsed.</returns>
        public static PatchStatusRegistrySnapshot DecodeRegistry(string json)
        {
            if (string.IsNullOrWhiteSpace(json))
                return null;

            try
            {
                using (JsonDocument document = JsonDocument.Parse(json))
                {
                    JsonElement root = document.RootElement;
                    if (root.ValueKind != JsonValueKind.Object)
                        return null;

                    PatchStatusRegistrySnapshot snapshot = new PatchStatusRegistrySnapshot
                    {
                        RawJson = json,
                        Type = ReadString(root, "type"),
                        Revision = ReadUInt64(root, "revision"),
                        AcceptedPeerId = ReadUInt32(root, "acceptedPeerId"),
                        TtlSeconds = ReadUInt32(root, "ttlSeconds")
                    };

                    if (root.TryGetProperty("peers", out JsonElement peers) && peers.ValueKind == JsonValueKind.Array)
                    {
                        foreach (JsonElement peer in peers.EnumerateArray())
                            snapshot.Peers.Add(ReadPeer(peer));
                    }

                    if (root.TryGetProperty("patches", out JsonElement patches) && patches.ValueKind == JsonValueKind.Array)
                    {
                        foreach (JsonElement patch in patches.EnumerateArray())
                            snapshot.Patches.Add(ReadPatch(patch));
                    }

                    if (root.TryGetProperty("byTalkgroup", out JsonElement byTalkgroup) && byTalkgroup.ValueKind == JsonValueKind.Object)
                    {
                        foreach (JsonProperty entry in byTalkgroup.EnumerateObject())
                        {
                            List<PatchStatusPatch> entries = new List<PatchStatusPatch>();
                            if (entry.Value.ValueKind == JsonValueKind.Array)
                            {
                                foreach (JsonElement tgPatch in entry.Value.EnumerateArray())
                                {
                                    PatchStatusPatch parsed = ReadPatch(tgPatch);

                                    // byTalkgroup entries carry a single "member" object rather than a members array
                                    if (tgPatch.TryGetProperty("member", out JsonElement member) && member.ValueKind == JsonValueKind.Object)
                                        parsed.Members.Add(ReadMember(member));

                                    entries.Add(parsed);
                                }
                            }

                            snapshot.ByTalkgroup[entry.Name] = entries;
                        }
                    }

                    return snapshot;
                }
            }
            catch (JsonException)
            {
                return null;
            }
        }

        /// <summary>
        /// Reads a peer patch snapshot from JSON.
        /// </summary>
        private static PatchStatusPeer ReadPeer(JsonElement element)
        {
            PatchStatusPeer peer = new PatchStatusPeer();
            if (element.ValueKind != JsonValueKind.Object)
                return peer;

            peer.PeerId = ReadUInt32(element, "peerId");
            peer.OriginFnePeerId = ReadUInt32(element, "originFnePeerId");
            peer.PeerName = ReadString(element, "peerName");
            peer.Sequence = ReadUInt32(element, "sequence");
            peer.UpdatedAt = ReadUInt64(element, "updatedAt");
            peer.ExpiresAt = ReadUInt64(element, "expiresAt");

            if (element.TryGetProperty("patches", out JsonElement patches) && patches.ValueKind == JsonValueKind.Array)
            {
                foreach (JsonElement patch in patches.EnumerateArray())
                    peer.Patches.Add(ReadPatch(patch));
            }

            return peer;
        }

        /// <summary>
        /// Reads a patch record from JSON.
        /// </summary>
        private static PatchStatusPatch ReadPatch(JsonElement element)
        {
            PatchStatusPatch patch = new PatchStatusPatch();
            if (element.ValueKind != JsonValueKind.Object)
                return patch;

            patch.PatchId = ReadString(element, "patchId");
            patch.Active = ReadBool(element, "active", true);
            patch.OneWay = ReadBool(element, "oneWay", false);
            patch.PeerId = ReadUInt32(element, "peerId");
            patch.OriginFnePeerId = ReadUInt32(element, "originFnePeerId");
            patch.PeerName = ReadString(element, "peerName");

            if (element.TryGetProperty("members", out JsonElement members) && members.ValueKind == JsonValueKind.Array)
            {
                foreach (JsonElement member in members.EnumerateArray())
                    patch.Members.Add(ReadMember(member));
            }

            return patch;
        }

        /// <summary>
        /// Reads a patch member from JSON.
        /// </summary>
        private static PatchStatusMember ReadMember(JsonElement element)
        {
            PatchStatusMember member = new PatchStatusMember();
            if (element.ValueKind != JsonValueKind.Object)
                return member;

            member.System = ReadString(element, "system");
            member.Mode = ReadString(element, "mode");
            member.Tgid = ReadUInt32(element, "tgid");
            member.Slot = ReadByte(element, "slot");
            member.Key = ReadString(element, "key");

            return member;
        }

        /// <summary>
        /// Reads a string property, returning an empty string when absent.
        /// </summary>
        private static string ReadString(JsonElement element, string name)
        {
            if (element.TryGetProperty(name, out JsonElement value) && value.ValueKind == JsonValueKind.String)
                return value.GetString() ?? string.Empty;

            return string.Empty;
        }

        /// <summary>
        /// Reads a boolean property, returning the supplied default when absent.
        /// </summary>
        private static bool ReadBool(JsonElement element, string name, bool defaultValue)
        {
            if (element.TryGetProperty(name, out JsonElement value))
            {
                if (value.ValueKind == JsonValueKind.True)
                    return true;
                if (value.ValueKind == JsonValueKind.False)
                    return false;
            }

            return defaultValue;
        }

        /// <summary>
        /// Reads a byte property, returning zero when absent or out of range.
        /// </summary>
        private static byte ReadByte(JsonElement element, string name)
        {
            if (element.TryGetProperty(name, out JsonElement value) && value.ValueKind == JsonValueKind.Number &&
                value.TryGetByte(out byte result))
                return result;

            return 0;
        }

        /// <summary>
        /// Reads a 32-bit unsigned integer property, returning zero when absent or not an integer.
        /// </summary>
        private static uint ReadUInt32(JsonElement element, string name)
        {
            if (element.TryGetProperty(name, out JsonElement value) && value.ValueKind == JsonValueKind.Number &&
                value.TryGetUInt32(out uint result))
                return result;

            return 0;
        }

        /// <summary>
        /// Reads a 64-bit unsigned integer property, returning zero when absent or not an integer.
        /// </summary>
        private static ulong ReadUInt64(JsonElement element, string name)
        {
            if (element.TryGetProperty(name, out JsonElement value) && value.ValueKind == JsonValueKind.Number &&
                value.TryGetUInt64(out ulong result))
                return result;

            return 0;
        }

        /// <summary>
        /// Decodes the UTF-8 JSON payload carried in a patch status transfer message.
        /// </summary>
        /// <param name="message">Raw FNE message, including the 11 byte transfer header.</param>
        /// <returns>JSON payload string, or an empty string when the message is too short.</returns>
        public static string ExtractPayload(byte[] message)
        {
            if (message == null || message.Length <= PATCH_STATUS_HEADER_LENGTH)
                return string.Empty;

            return Encoding.UTF8.GetString(message, PATCH_STATUS_HEADER_LENGTH,
                message.Length - PATCH_STATUS_HEADER_LENGTH).TrimEnd('\0');
        }

        /// <summary>
        /// Wraps a UTF-8 JSON payload in the 11 byte transfer header the FNE expects.
        /// </summary>
        /// <param name="payload">UTF-8 encoded JSON payload.</param>
        /// <returns>Raw FNE message.</returns>
        public static byte[] WrapPayload(byte[] payload)
        {
            if (payload == null)
                throw new ArgumentNullException(nameof(payload));

            byte[] message = new byte[payload.Length + PATCH_STATUS_HEADER_LENGTH];
            Buffer.BlockCopy(payload, 0, message, PATCH_STATUS_HEADER_LENGTH, payload.Length);

            return message;
        }

        /// <summary>
        /// Length, in bytes, of the unused transfer header preceding a patch status payload.
        /// </summary>
        /// <remarks>
        /// dvmhost reads transfer payloads starting at offset 11 of the message; the leading bytes are
        /// not inspected. See BaseNetwork::writeActLog() and MetadataNetwork::taskNetworkRx().
        /// </remarks>
        public const int PATCH_STATUS_HEADER_LENGTH = 11;
    } // public static class PatchStatusCodec
} // namespace fnecore
